"""Render the individually assessed products using this audit's fetched evidence."""
from pathlib import Path
import json

ROOT=Path(__file__).resolve().parent
pages={r['url']:r for r in json.loads((ROOT/'pages.json').read_text())}
groups={
'Business workflow tools':[
('ledgermatch','LedgerMatch','PRIORITIZE','Reconcile a supplier statement with the buyer’s ledger.','An accounting firm reconciles an authorized real statement, checks every exception, and chooses repeated paid use over its existing spreadsheet.','Existing hosting/Stripe; fix outcome measurement.'),
('qrelay','QRelay','PRIORITIZE','Reduce repeated work answering customer security questionnaires.','A B2B vendor completes a real questionnaire with attributable approved answers, useful export and less rework; measure repeated use.','Existing hosting/Stripe; recipient messages remain human-sent.'),
('casepack','CasePack','CONDITIONAL','Let a wholesaler’s retailers create bilingual case reorders.','A wholesaler embeds it and gets accurate repeat reorder requests from actual retailers. A generated sheet is insufficient.','Existing services; no extra login established.'),
('acacheck','ACACheck','CONDITIONAL','Catch supported ACA transmission-file defects before filing.','A payroll implementer supplies permitted known-error/known-good files and independently validates findings against the actual submission specification.','No IRS or client account requested merely to validate local files.'),
('schemahand','SchemaHand','CONDITIONAL','Produce a useful database handoff for a consultancy’s client.','A receiving developer uses the export to complete a real maintenance task more effectively than existing diagram tools.','Existing services; an absent public seed repo is a distribution task.'),
('catalog-migration','Catalog migration','PRIORITIZE','Convert a bounded source catalog into explicit destination import files.','A disposable Shopify import preserves products, variants and identifiers exactly; then a merchant confirms material migration value and pays for protected delivery.','Conditional Shopify developer/test-store access; no client production store needed yet.'),
],
'Tools with store distribution or unfinished store paths':[
('kdp-lens','KDP Lens','PRIORITIZE','Show book-market estimates within the publisher’s browsing workflow.','A real publisher installs it, understands estimate limits, uses it for a repeated decision and pays; compare against free tools.','Chrome API access exists. Gumroad/AppSumo are optional further channels.'),
('grant-fit','Grant Fit','CONDITIONAL','Help nonprofit staff reject poor-fit funding opportunities before writing applications.','A grants team compares actual go/no-go decisions with its current process and finds material time saved without misleading eligibility assertions.','Chrome API and hosted service exist; paid inference is a cost boundary, not a missing login.'),
('notice-responder','Notice Responder','HOLD','Explain supported notice text and organize a response pack.','Independent notice-specific correctness and an actual useful recipient workflow are required; a generic generated letter cannot establish quality.','No new tax-agency login. Validate product scope before distribution.'),
('warn-right','WarnRight','HOLD','Support a Shopify merchant’s applicable warning workflow.','Inspect the actual product contract, install in an isolated merchant test store, and demonstrate the specific warning behavior without unsupported assurance.','Shopify app/test-store registration is conditional; no store link is present on the fetched page.'),
('done-means-done','Done Means Done','HOLD','Improve Jira ticket acceptance criteria.','An engineering team catches meaningful ambiguous requirements and reduces rework; compare against a simple checklist before building more app infrastructure.','Atlassian app ID is a placeholder. Developer access is conditional, not the first business test.'),
('apify-public-records','EPA public-record actor','CONDITIONAL','Deliver a reusable clean drinking-water-system table through a discoverable store.','An external analyst runs the actor successfully, receives current accurate rows, returns, and pays; show value over the original free data download.','Apify API access exists; direct detail says public and not deprecated. No login needed.'),
('apify-public-records','OSHA and NRC actors','HOLD','Potential repeatable public-record extraction.','They are deprecated in current direct API reads. Do not revive them without a lawful source, correct output, pricing check and a concrete buyer task.','No new access. Account access does not repair deprecated products.'),
('customs-broker-exam-bank','Customs Broker Exam Bank','CONDITIONAL','Help a candidate study with traceable official answers and correct explanations.','Verify every offered explanation and edition, deliver the promised file, and observe study usefulness plus purchases from exam candidates.','Gumroad payout setup is a confirmed owner dependency. A listing alone is not demand.'),
],
'Directories and quote-based compliance products':[
('city-trade','City Trade','HOLD','Connect a local trade buyer to the relevant local business.','Actual qualified inquiries attributable to the page must benefit a listed business. More city pages and search counts alone do not justify subscriptions.','No new login. Remove recurring manual reporting/delivery dependency before expansion.'),
('enforcement-action-board','Enforcement Action Board','HOLD','Help affected facilities find relevant enforcement records and assistance.','Real facility users consult the board and generate attributable qualified inquiries for a provider. Paid mentions alone do not establish a differentiated new path.','No additional access established; source freshness and delivery matter.'),
('patent-practitioner-directory','Patent Practitioner Directory','HOLD','Help a relevant client find an appropriate practitioner.','Attributed qualified practitioner inquiries and correct directory data; paid-listing revenue is the same mention-for-pay pattern, not a new moat by itself.','Do not reopen USPTO login. Confirm source rights/freshness within existing restrictions.'),
('trademark-watch','Trademark Watch','DROP','Previously proposed trademark monitoring.','Operator dropped USPTO permanently; do not revive this lane as a missing-access task.','No USPTO signup, MFA or API request.'),
('hazmat-ship-pack','Hazmat Ship Pack','HOLD','Provide supported source rows and a road-shipping worksheet.','An appropriately qualified user independently checks the bounded worksheet for its real use case; a generated form or citation is not a safety verdict.','No shipping-company login needed to establish output correctness. Keep any uncertain lawful use parked.'),
('contractor-audit-file','Contractor Audit File','CONDITIONAL','Organize a business’s facts, source quotations and documents for review.','A real business/reviewer finds the file materially reduces preparation effort while clearly avoiding a classification verdict.','Existing payment/delivery path; no tax authority login required.'),
('nutrition-label-forge','Nutrition Label Forge','HOLD','Generate supported panel calculations from explicit inputs.','Independent known-recipe calculation and rendering validation, plus food-maker acceptance; no claim of regulatory approval from a generated label.','No new login solves correctness, ingredient coverage or interpretation.'),
('ai-disclosure-notice','AI Disclosure Notice','HOLD','Organize supported quoted rules and bounded notice text.','A buyer and qualified reviewer find a precise, current, useful notice package materially better than existing templates.','No additional account. Source currency and truthful scope first.'),
('notary-journal','Notary Journal','CONDITIONAL','Give a notary a local journal with protected export/recovery.','A permitted real workflow demonstrates reliable entry, backup, recovery and repeated use; browser-local storage is not enough by itself.','No new login established; independent correctness and recovery checks first.'),
],
'Historical-data and recurring feed candidates':[
('carrier-register','Carrier Register','CONDITIONAL','Help trucking insurers or factoring teams identify newly authorized carriers.','A team identifies timely relevant businesses using the changes and proves a material advantage over direct source alerts.','Existing collector/subscription rail; no paid enrichment assumed.'),
('dealer-licence','Dealer Licence','CONDITIONAL','Help dealer-service vendors track relevant new/lapsed licenses.','An actual vendor uses accurate weekly changes in a recurring workflow and pays for the advantage.','Existing collector/rail; no new browser account established.'),
('stormwater-noi','Stormwater NOI','CONDITIONAL','Help local construction suppliers find relevant newly started sites.','A branch manager validates freshness, geographic coverage and usefulness on actual jobs, beyond the public source’s own interface.','Existing data and collector; qualified outcomes first.'),
('hts-revision-seal','HTS Revision Seal','CONDITIONAL','Preserve exact dated tariff-source versions for later reference.','A broker/auditor retrieves the exact needed historical text and values the retained history over available official archives.','No new login established; source rights, provenance and repeat retrieval matter.'),
('cannabis-tape','Cannabis Tape','CONDITIONAL','Provide dated licensing changes for relevant suppliers and insurers.','Correct change history improves a permitted buyer task and wins repeat paid use.','No new access established. Lawful collection and use must remain established.'),
('new-prime-awards','New Prime Awards','CONDITIONAL','Let suppliers identify relevant new contract award holders.','A supplier filters actual relevant awards faster/better than its existing government-source workflow and pays.','No SAM.gov signup needed simply to prove an already-collected-data product.'),
('storm-warned-counties','Storm Warned Counties','HOLD','Provide dated warning coverage for a service territory.','A buyer demonstrates advantage over existing free weather information; a weekly warning list alone is weak differentiation.','No new access. Keep forecast/safety claims bounded.'),
('ttb-new-permits','TTB New Permits','HOLD','Identify relevant newly permitted alcohol businesses.','A buyer task must beat the convenient official free file; finish automatic delivery before calling it autonomous.','Existing access; fetched/source copy still promises person-emailed delivery.'),
('fda-device-establishment-week','FDA Device Establishment Week','CONDITIONAL','Preserve registration-change evidence for distributors and compliance teams.','A buyer verifies a needed historical change and pays for the retained comparison, without treating registration as product approval.','No new login established; current delivery promise includes human emailing.'),
('hospital-mrf','Hospital MRF archive — recovered','CONDITIONAL','Preserve dated hospital source files for historical comparisons.','An authorized buyer demonstrates a concrete historical-reference need not met by current files.','Existing archive/payment infrastructure; recent work was recovery, not proof of a new business.'),
('model-cards','Model Cards archive — recovered','CONDITIONAL','Preserve dated model-provider claim text for procurement review.','A procurement reviewer uses a historical change that current vendor pages cannot reproduce conveniently.','Existing infrastructure; no more model-provider logins just to publish quotes.'),
('texas-formulary','Texas Formulary archive — recovered','CONDITIONAL','Preserve dated source versions for market-access reference.','A specialist buyer validates the exact historical question and usefulness; no clinical guidance is inferred.','Existing infrastructure; recovered pages are not fresh demand.'),
('quakes','Quakes archive — recovered','HOLD','Preserve dated earthquake-source observations.','Identify a repeat paid task where the archive improves on authoritative free data; reconcile actual delivery and current price before expansion.','No new browser login. Do not change sale status based on this advisory review.'),
],
'Other scheduling, scan and proof surfaces':[
('changeover-atlas','Changeover Atlas','CONDITIONAL','Help a production planner reduce sequence-dependent setup work.','Use the planner’s real constraints and measured setup times, validate feasibility, and show material improvement over the current schedule.','No new login. Generic weekly emailed files do not provide autonomous customer-specific scheduling.'),
('pilot-logbook-digitizer','Pilot Logbook Digitizer','HOLD','Convert permitted logbook material into a correct importable record.','Independent row/total reconciliation and target-app import from actual authorized input, with an automatic upload/review/download path.','Current offer requires receipt-email attachments and manual return. No login repairs that architecture.'),
('wp-accessibility-scan','WordPress Accessibility Scan','CONDITIONAL','Find bounded, actionable problems on a buyer’s own site.','A site owner fixes meaningful defects from the output and values a repeated scan beyond free tools; automated scanning is not full accessibility certification.','No WordPress administrator access needed for an authorized public-page scan.'),
('machine-visitor-ledger','Machine Visitor Ledger','HOLD','Summarize identified machine-user-agent activity in supplied logs.','A real operator task must show value over the already demonstrated free-log-analyzer substitute; synthetic traffic is not demand.','No new login. Do not turn bot counts into client counts.'),
('access-affidavits','Access Affidavits','HOLD','Provide a bounded evidence pack about an observed access surface.','An identified buyer validates the evidence is useful and repeatable; a legal-sounding title does not establish legal effect.','Human delivery is visible; no account request before buyer and delivery proof.'),
('address-packet','Address Packet','HOLD','Organize relevant public records for an exact address.','A permitted real address task demonstrates correct coverage and useful output without manual research per order.','No new login; manual email fulfillment remains a mismatch.'),
('clean-room-corpus','Clean Room Corpus','HOLD','Supply a bounded, source-permitted corpus.','An identified user actually consumes it with documented rights and measurable task value.','No new account. Corpus size and a page do not establish usefulness.'),
('clerk-clock','Clerk Clock','HOLD','Provide a bounded dated record/timing pack.','Clarify and test the exact buyer task against real source evidence; no inferred deadline assurance.','Current public text indicates manual delivery; no login-first work.'),
('frozen-custody','Frozen Custody','HOLD','Preserve a dated evidence snapshot.','A buyer demonstrates a repeat need for the exact retained bytes and provenance; no legal-custody effect is inferred.','No new account; automate the actual delivery only after value is shown.'),
('predictor-diet','Predictor Diet','HOLD','Offer a bounded dataset/evidence pack.','Prove an identified user task, actual data advantage and repeat use; the offer label is not a product-quality finding.','No new access; public text still indicates human delivery.'),
('stamper-appendix','Stamper Appendix','HOLD','Organize public-record source quotations for a professional’s own filing.','An actual professional finds a repeated preparation advantage and independently checks the quotes; the product is not a professional stamp.','No new access. Manual delivery and one-off preparation conflict with the desired model.'),
('wrong-wall','Wrong Wall','HOLD','Provide a bounded record/evidence product.','Identify and independently validate the concrete buyer outcome before investing in more pages or processing.','No login-first work; current text indicates manual delivery.'),
],
'Original production engines — intended family URLs returned 404':[
('pressnest','PressNest','HOLD','Create bounded print-sheet raster layouts and placements.','A print operator accepts an actual output and achieves useful material/setup savings over its existing nesting tool.','Public portal/payment settlement still need implementation/configuration; no specific missing browser login proven.'),
('optionforge','OptionForge','CONDITIONAL','Create a portable configurator from explicit compatibility constraints.','A vendor embeds and uses it to produce correct actual customer configurations, improving its quoting workflow.','Public portal/payment path incomplete; select only after buyer test.'),
('branchlab','BranchLab','HOLD','Export a branching lesson and bounded SCORM package.','The actual target LMS imports and tracks the package correctly for a real trainer’s lesson.','Conditional test-LMS access; no generic new account without a target importer.'),
('choicebench','ChoiceBench','HOLD','Create a bounded survey and supported response analysis.','An appropriate user validates design and interpretation against their actual decision; synthetic analysis is not business evidence.','No new login established; public settlement and real-user acceptance missing.'),
('cueport','CuePort','HOLD','Transform supported timed-text files with exact validation.','A localization team accepts the output in its target player/editor and prefers it over free conversion tools.','Authorized target-format sample first; no generic login request.'),
],
'Export engines — local service, intended family URLs returned 404':[
('kitclear','KitClear','CONDITIONAL','Allocate available material and expose shortages for existing assembly orders.','A manufacturer verifies the result against a real BOM/order/stock set and avoids meaningful planning work or shortages.','Shared runtime key drift and public origin remain; no automatic demand inference from fixing them.'),
('roundplan','RoundPlan','HOLD','Generate feasible adult-league fixtures and repair reports.','A league accepts all real scheduling constraints and uses the result instead of its existing scheduling product.','Same closed runtime/public-origin gap; no additional login proven.'),
('staymatch','StayMatch','CONDITIONAL','Reconcile rooming lists by exact identifiers and reversible patches.','A hotel/event operator resolves actual discrepancies safely and accepts the output in its real workflow.','Same runtime/public-origin gap; customer system access only after a scoped integration need.'),
('threadkeep','ThreadKeep','HOLD','Build a searchable offline archive from already normalized permitted forum JSON.','A real archive owner can supply the supported input and finds preservation/search value; raw-backup import is not implemented.','No forum credentials requested to disguise missing normalization/import support.'),
('meshship','MeshShip','HOLD','Package approved static geometry into a portable GLB and viewer.','A buyer can supply the supported geometry and uses the delivered asset in the actual target application. It does not convert CAD.','No new login. Input-format fit must be demonstrated first.'),
],
'PathLab — public examples, public processing catalog returned 503':[
('gaugestudy','GaugeStudy','CONDITIONAL','Produce a bounded industrial measurement-study output.','A qualified measurement practitioner validates actual inputs and interpretation independently, and finds a material workflow gain.','PathLab key drift and public origin; specialist quality is not an account issue.'),
('shelfset','ShelfSet','CONDITIONAL','Produce a bounded retail shelf-reset layout/output.','A store planner verifies fit and actual reset usefulness against the existing process.','PathLab shared gaps; real input and target workflow first.'),
('lensgrid','LensGrid','HOLD','Prepare a bounded lens-calibration workflow/output.','A VFX user validates actual calibration data and target-tool acceptance, not only synthetic geometry.','PathLab shared gaps; no generic camera/VFX login requested.'),
('plateweave','PlateWeave','HOLD','Generate bounded nonclinical research layouts.','A qualified research user validates the exact design constraints and practical import/output, with no clinical-use claims.','PathLab shared gaps; domain quality first.'),
('samplemap','SampleMap','HOLD','Prepare supported audio samples for an instrument workflow.','A producer imports actual permitted samples into the stated target workflow and prefers the result over existing tools.','PathLab shared gaps; sample rights and target-format acceptance first.'),
],
'Workshop — browser tools, paid-kit catalog returned 503':[
('localewitness','LocaleWitness','CONDITIONAL','Generate bounded en/fr ICU branch fixtures and release comparisons.','A localization team catches meaningful actual release regressions and adopts the fixtures in its existing checks.','Browser operation needs no account; paid offline-kit delivery remains unconnected.'),
('treadleforge','TreadleForge','HOLD','Derive minimum treadles for a supported rising-shed liftplan.','An actual supported loom/workflow accepts the WIF and a weaver validates equivalence and practical value.','No browser login needed; niche demand and paid-kit delivery unproven.'),
('transitgap','TransitGap','CONDITIONAL','Evaluate explicit GTFS service-date and delay-connection scenarios.','A transit analyst validates a real supplied feed/scenario and finds actionable planning value beyond existing tools.','Browser operation needs no account; no live-service guarantee inferred.'),
('boardpose','BoardPose','CONDITIONAL','Produce supported PCB panel transforms and logical feeder assignments.','A manufacturing engineer independently validates a supported actual panel/machine workflow and accepts the export.','No new login; physical machine compatibility is not established by JSON output.'),
('tracefixture','TraceFixture','CONDITIONAL','Generate deterministic offline packet fixtures for supported protocols.','A team adopts the fixtures in actual regression checks and catches a meaningful parsing defect.','No network transmission or login required; paid-kit route incomplete.'),
],
'Archive prototypes — intended family URLs returned 404':[
('patch-crossfire','Patch Crossfire','HOLD','An archived proof/repair hypothesis.','Establish its actual supported input/output contract and a real requested task before reviving it.','No access request justified by a prototype page.'),
('rule-interval-atlas','Rule Interval Atlas','HOLD','A bounded historical-rule/interval prototype.','An identified user verifies a real historical question and values the result beyond source lookup.','No new access established.'),
('treasury-unit-reconcile','Treasury Unit Reconcile','HOLD','A bounded reconciliation prototype.','An authorized real fixture must validate units and usefulness for the actual intended buyer.','No new access established; no financial correctness certification.'),
('withdrawn-reference-index','Withdrawn Reference Index','HOLD','A withdrawn-reference/history prototype.','An identified specialist uses a correctly sourced historical reference unavailable conveniently elsewhere.','No new login established.'),
],
'Additional September 8 contracts and local experiment':[
(None,'Video salvage','HOLD','A local bounded Baseline H.264 parser experiment.','Reproduce actual known-original damaged files and outperform existing repair tools; arbitrary video repair is not implemented.','No account required for authorized fixture testing.'),
(None,'Bounded software repair','HOLD','Contract only, not an implemented business.','A permitted reproducible upgrade defect and constrained repair with independent acceptance.','No access until a specific authorized repository/task is selected.'),
(None,'Finishing-trade takeoffs','HOLD','Contract only.','A real permitted plan with known geometry, explicit scale and an independently accepted quantity result.','No generic construction-platform login.'),
(None,'EPUB reconstruction','HOLD','Contract only.','A rights-cleared source and destination-reader semantic acceptance that improves on available tools.','No store/publisher login before a prototype and buyer task.'),
(None,'Parametric CAD','HOLD','Contract only.','An available kernel, actual buyer geometry and independent constraint/target-import acceptance.','No CAD subscription purchase or account request.'),
(None,'Executable vendor demos','HOLD','Contract only.','A vendor supplies a permitted product-state contract and demonstrates a materially better qualified buyer journey.','No customer production access needed for a proposed simulation.'),
(None,'Incident practice packs','HOLD','Contract only.','A realistic authorized fault/reset/repair exercise improves the intended team’s demonstrated response skill.','No production infrastructure access requested.'),
(None,'Workload optimization','HOLD','Contract only.','A representative permitted baseline and a safe constrained transformation with an independently measured material improvement.','No additional compute spending or production access before bounded evidence.'),
(None,'Procedural components','HOLD','Contract only.','A concrete buyer feature gap plus known-answer constraints and actual target acceptance.','No generic additional account.'),
],
}

lines=['# Individual product decisions — September 9, 2026','',
'These are recommendations, not production state changes. No newer product has demonstrated retained paying-client impact in the examined evidence. Each row states the result that would justify further work. Some adjacent earlier/recovered products are included to avoid losing relevant dependencies.','',
'HTTP statuses are observations of the named family URL, not tests of a purchase or the full engine. LOCAL/CONTRACT means no public product URL was asserted here. The business tests below remain outstanding unless the main review says otherwise.','']
data=[]
for group,rows in groups.items():
    lines+=['## '+group,'','| Product / current family HTTP | Judgment | Customer result and decisive test | Access or implementation dependency |','|---|---|---|---|']
    for slug,name,decision,value,test,dep in rows:
        url='https://ustechautomations.com/feeds/'+slug+'/' if slug else None
        probe=pages.get(url,{})
        status=str(probe.get('status','UNKNOWN')) if slug else 'LOCAL/CONTRACT'
        # Only offer a clickable public URL when this run fetched HTTP 200.
        label=f'[{name}]({url})' if probe.get('status')==200 else name
        lines.append(f'| {label} — {status} | {decision} | {value} **Test:** {test} | {dep} |')
        data.append(dict(group=group,slug=slug,name=name,decision=decision,value=value,test=test,dependency=dep,url=url,http=probe.get('status')))
    lines+=['']
lines+=['## Source basis','',
'Family names and stated buyer tasks were read from the current feeds catalog, the four independent product README/contract sets, marketplace source and the ten-path compiler contract. Existing source artifacts establish intended behavior; this audit does not repeat every engine’s acceptance tests. Historical `sample_status` labels and test-count claims were not treated as real customer proof.','',
'- `/home/gmullins/code/usta-paid-surfaces/catalog.json` and `fv5/`, `loops/`.','- `/home/gmullins/code/market-products/`.','- `/home/gmullins/grok-playground/worktrees/five-systems-01a07df1/README.md`.','- `/home/gmullins/grok-playground/worktrees/new-five-20260907/README.md`.','- `/home/gmullins/grok-playground/worktrees/new-five-20260908-b/README.md`.','- `/home/gmullins/grok-playground/worktrees/new-five-20260908-c/docs/STATUS.md`.','- `/home/gmullins/code/ten-path-builds-20260908/README.md`, `DECISIONS.json`, `HANDOFF.md`.','',
'Hubs (`feeds`, `new-five`, `pathlab`, `workshop`), bundle access, thanks pages and child pages are support surfaces, not additional businesses. The main review separately assesses infrastructure, access and distribution.','']
(ROOT/'products.md').write_text('\n'.join(lines))
(ROOT/'product-decisions.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
print(json.dumps({'assessed_rows':len(data),'by_recommendation':{k:sum(x['decision']==k for x in data) for k in sorted({x['decision'] for x in data})}}))
