"""changeover-atlas: one page, one weekly generated file, no child pages.

The file is NOT read from the world. scripts at ~/.hermes/scripts/changeover_atlas_build.py
writes ~/.hermes/state/changeover-atlas/atlas_<date>.csv (+ .json) from a dated seed:
24 bounded scheduling instances (1-3 machines, 6-12 jobs, four changeover rule families)
with the naive job order, the best order the solver found, and the minutes saved.
The page says so in its first paragraph, and every count below is read off the newest
pack on disk at build time.

Sample rule: the newest pack with the `sequence` column removed. A visitor sees every
shape and every saving; the paid file adds the order to run.
"""
from __future__ import annotations

import csv
import glob
import html
import os
import re
import sys
import urllib.parse
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_family import section, table  # noqa: E402

FAMILY = "changeover-atlas"
STORE = Path(os.path.expanduser("~/.hermes/state/changeover-atlas"))
PAID_COL = "sequence"
TABLE_CAP = 12
MAX_DESC = 155
CLASS_WORDS = {
    "colour-sequence": "colour sequence",
    "size-progression": "size progression",
    "allergen-cleandown": "allergen clean-down",
    "tool-family": "tool family",
}

_ROWS: list[dict] | None = None
_FILE: Path | None = None


def _e(s) -> str:
    return html.escape(str(s), quote=True)


def _d(iso: str) -> str:
    y, m, d = (int(x) for x in iso[:10].split("-"))
    return date(y, m, d).strftime("%-d %b %Y")


def newest_pack() -> Path:
    files = sorted(glob.glob(str(STORE / "atlas_*.csv")))
    if not files:
        raise RuntimeError(f"{FAMILY}: no pack at {STORE}/atlas_*.csv; run changeover_atlas_build.py first")
    return Path(files[-1])


def rows() -> list[dict]:
    global _ROWS, _FILE
    if _ROWS is None:
        _FILE = newest_pack()
        with _FILE.open(newline="", encoding="utf-8") as fh:
            _ROWS = list(csv.DictReader(fh))
        need = {"instance_id", "snapshot_date", "changeover_class", "machines", "jobs",
                "naive_changeover_min", "best_changeover_min", "saved_min", "saved_pct", PAID_COL}
        missing = need - set(_ROWS[0].keys() if _ROWS else ())
        if missing or not _ROWS:
            raise RuntimeError(f"{FAMILY}: pack {_FILE} is missing columns {sorted(missing)} or is empty")
    return _ROWS


def snapshot_date() -> str:
    return rows()[0]["snapshot_date"][:10]


def slices() -> list[dict]:
    """No child pages: one weekly file, one page."""
    return []


def sample() -> tuple[list[str], list[list[str]]]:
    """The public sample: the newest pack, sequence column left out."""
    r = rows()
    headers = [h for h in r[0].keys() if h != PAID_COL]
    return headers, [[row[h] for h in headers] for row in r]


def _by_class() -> list[list[str]]:
    agg: dict[str, list[dict]] = {}
    for row in rows():
        agg.setdefault(row["changeover_class"], []).append(row)
    out = []
    for cls, rs in sorted(agg.items()):
        naive = sum(int(x["naive_changeover_min"]) for x in rs)
        best = sum(int(x["best_changeover_min"]) for x in rs)
        pct = (100.0 * (naive - best) / naive) if naive else 0.0
        out.append([CLASS_WORDS.get(cls, cls), str(len(rs)), f"{naive:,}", f"{best:,}", f"{naive - best:,}", f"{pct:.0f}%"])
    return out


def family_spec() -> dict:
    r = rows()
    snap = snapshot_date()
    stamp = f"pack of {_d(snap)}"
    total_naive = sum(int(x["naive_changeover_min"]) for x in r)
    total_best = sum(int(x["best_changeover_min"]) for x in r)
    saved = total_naive - total_best
    pct = (100.0 * saved / total_naive) if total_naive else 0.0
    shapes = sorted({(int(x["machines"]), int(x["jobs"])) for x in r})
    head = ["Instance", "Rule family", "Machines", "Jobs", "Naive minutes", "Best found", "Saved", "Saved %"]
    body = [[x["instance_id"], CLASS_WORDS.get(x["changeover_class"], x["changeover_class"]), x["machines"], x["jobs"],
             x["naive_changeover_min"], x["best_changeover_min"], x["saved_min"], f'{float(x["saved_pct"]):.0f}%']
            for x in sorted(r, key=lambda x: -int(x["saved_min"]))]
    desc = (f"{len(r)} generated changeover-scheduling instances a week, 1-3 machines, 6-12 jobs, "
            f"with the best job order our solver found. Pack of {_d(snap)}. $49/mo.")
    assert len(desc) <= MAX_DESC, len(desc)
    secs = [
        section(
            "What is in this week's file",
            f"{len(r)} instances, {stamp}",
            "      <p><strong>Nothing on this page was measured in a real factory.</strong> Every instance "
            "below was generated by our own solver from a dated seed. The changeover minutes are made up "
            "to be plausible for the rule family named; the saving is real arithmetic on those made-up "
            "minutes. You pick the instance whose shape matches your shop and use its order as a starting "
            "guess, then re-run the same arithmetic on your real changeover times to see if it still wins. "
            "The order was worked out on made-up minutes, so it is a head start, not an answer. The "
            "<em>Saved %</em> column shows how much the job order matters for that shape; it is not what "
            "your shop will save.</p>\n"
            + table(head, body[:TABLE_CAP], f"{min(TABLE_CAP, len(r))} of the {len(r)} instances, biggest saving first", stamp)
            + '\n      <div class="honest">\n'
            f"        <p><strong>Across all {len(r)} instances the naive order costs {total_naive:,} changeover "
            f"minutes and the best order we found costs {total_best:,}, a saving of {saved:,} minutes "
            f"({pct:.0f}%).</strong> \"Best found\" means best our search found, not proven optimal. "
            "A different solver may find better.</p>\n"
            "      </div>",
        ),
        section(
            "Saving by rule family",
            f"{len({x['changeover_class'] for x in r})} rule families in this pack",
            "      <p>Summed across the instances in each family, this pack only.</p>\n"
            + table(["Rule family", "Instances", "Naive minutes", "Best found", "Saved", "Saved %"], _by_class(),
                    "All four rule families", stamp),
        ),
        section(
            "What you get",
            None,
            '      <ul class="spec">\n'
            "        <li><strong>One file a week</strong>"
            f'<span class="sub">{len(r)} instances: {", ".join(f"{m} machine{"s" if m > 1 else ""} x {j} jobs" for m, j in shapes[:4])} and on up to '
            f'{shapes[-1][0]} machines x {shapes[-1][1]} jobs, in each of the four rule families.</span></li>\n'
            "        <li><strong>Eleven columns</strong>"
            '<span class="sub">Instance id, pack date, rule family, machines, jobs, naive minutes, best-found minutes, '
            "minutes saved, saved %, the busiest machine's minutes (how long the most-loaded machine runs, "
            "so you can see the bottleneck), and the sequence to run per machine. The free sample carries "
            "the first ten; the sequence column is the one you pay for.</span></li>\n"
            "        <li><strong>The matrix behind every row</strong>"
            '<span class="sub">A JSON twin of the file carries each instance\'s job labels, the full changeover-minutes matrix, '
            "the naive order and the best order, so you can re-check the arithmetic.</span></li>\n"
            "        <li><strong>The free sample is this week's file without the sequence column</strong>"
            '<span class="sub">Every shape and every saving is public. The order to run is what you pay for.</span></li>\n'
            "      </ul>\n"
            '      <div class="honest">\n'
            "        <p><strong>Limits, plainly.</strong> The instances are generated, not measured. The shapes are "
            "bounded: at most 3 machines and 12 jobs. The minutes are synthetic. Best found is not proven optimal. "
            "Nothing is built for your factory: you match a shape and take its order as a starting point, then "
            "check it on your own minutes. If your shop has more machines, "
            "more jobs, or changeover times that depend on more than the job before, this file does not fit.</p>\n"
            f"        <p><strong>Newest pack dated {_d(snap)}.</strong> If the next weekly pack does not get built, "
            "this page says so instead of showing the old one as new.</p>\n"
            "      </div>",
        ),
    ]
    return {
        "id": FAMILY,
        "ready": True,
        "group": "Other dated records",
        "cadence": "weekly, every Monday",
        "cadence_long": ("one generated pack a week, built every Monday from that week's dated seed. "
                         "A pack always holds 24 instances or the build fails and the page says so"),
        "crumb": "Changeover atlas",
        "h1": "Changeover schedule atlas: 24 solved scheduling instances a week",
        "buyer": ("Planners and owner-operators at small manufacturers who search for production "
                  "scheduling templates and changeover reduction spreadsheets"),
        "desc": desc,
        "lede": (f"{len(r)} small production-scheduling instances, generated on {_d(snap)}, each with the job "
                 f"order a planner would naively run and the best order our solver found. Together they save "
                 f"{saved:,} synthetic changeover minutes ({pct:.0f}%). Nothing here was measured in a real factory."),
        "pill_label": "Sample ready",
        "sections": secs,
        "sample_dt": "Public sample",
        "subj": urllib.parse.quote("Changeover schedule atlas weekly file"),
        "contact_h2": "Start the thread",
        "contact_p": ("Ask which shapes this week's pack holds. We reply with the instance list and the "
                      "saving per rule family before you spend anything."),
        "contact_cta": "Ask which shapes are in this week's pack",
        "contact_note": "We tell you the shapes and the savings before you pay.",
        "foot": ("Every count on this page was read off the dated pack named above. The pack is generated by our "
                 "solver, not measured from any factory, and the page says so wherever a number appears."),
        # The shared template says a sample is "not made up"; here the minutes are, by design.
        "sample_note": ("straight out of this week's pack. The minutes are solver-made, like every figure "
                        "here; these are the real pack rows, not a tidied demo."),
        "sample_rest": ("the growing library. Every past week's 24 solved shapes stay yours, so over time "
                        "you build a bank of orders to match against"),
        "delivery": ("<strong>What arrives after you pay:</strong> After you pay, Stripe sends you to a page "
                     "carrying your own payment reference. That week's file appears at that address, and a new "
                     "one each week for as long as the subscription runs. A week we could not build says so "
                     "rather than repeating the last one. Nobody emails you."),
    }


def _main() -> int:
    r = rows()
    hdr, srows = sample()
    assert all(len(x) == len(hdr) for x in srows)
    assert PAID_COL not in hdr
    spec = family_spec()
    assert len(spec["desc"]) <= MAX_DESC
    print(f"family   {FAMILY}")
    print(f"pack     {_FILE}  ({len(r)} instances, dated {snapshot_date()})")
    print(f"sample   {len(srows)} rows, {len(hdr)} columns; desc {len(spec['desc'])} chars")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
